//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.TestAppointments = new HashSet<TestAppointment>();
            this.TestQuestions = new HashSet<TestQuestion>();
        }
    
        public int id { get; set; }
        public int teacher { get; set; }
        public System.DateTime createTime { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double Min5 { get; set; }
        public double Min4 { get; set; }
        public double Min3 { get; set; }
        public System.DateTime defaultExecutionTime { get; set; }
        public int defaultAttemptCount { get; set; }
    
        public virtual TeacherWorkload TeacherWorkload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestAppointment> TestAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
    }
}
