//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerVariant
    {
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public int answer { get; set; }
        public int variant { get; set; }
        public string variantText { get; set; }
    
        public virtual Answer Answer1 { get; set; }
        public virtual Variant Variant1 { get; set; }
    }
}
